### ISSUE TITLE
Update Github links to point to the Backstroke organisation

### ISSUE THREAD

**Issue by 1egoman** [backstrokeapp/www#1]
There are a couple Github links throughout [Backstroke's website](https://backstroke.co/) that point to `https://github.com/1egoman/backstroke`. Instead, they should point to the new Backstroke GitHub organization: `https://github.com/backstrokeapp`.

Here's how to build the website locally: https://github.com/backstrokeapp/www#development

Thanks!

**Comment by Mszauer** [comment]
I'd love to help out on this. Going to get started now.
