### ISSUE TITLE
Adjust the inner border radius to the Backstroke logo

### ISSUE THREAD

**Issue by 1egoman** [backstrokeapp/www#4]
<img width="616" alt="screen shot 2017-10-09 at 6 46 33 am" src="https://user-images.githubusercontent.com/1704236/31334777-b2a66c28-acbd-11e7-9057-c2257c2fc19b.png">

The new Backstroke logo has the same inner border radius as it does the outer border radius. Ideally, the inner border radius would be smaller such that the outer border visually looks to be the same width, even throughout the corners.

If you'd like to play around with border radii before changing, here's a tool that lets you visualize them: http://joshnh.com/tools/get-your-nested-border-radii-right.html

Here are a list of files that this change should be applied to:

https://github.com/backstrokeapp/www/blob/master/assets/img/logo.svg
https://github.com/backstrokeapp/www/blob/master/assets/img/logo.png
https://github.com/backstrokeapp/www/blob/master/assets/img/inverse.png
https://github.com/backstrokeapp/www/blob/master/assets/img/Inverse.svg
https://github.com/backstrokeapp/dashboard/blob/master/src/images/Logo.png

Most if not all of these files should have vector counterparts that should let you make your adjustments in there, then all you need to do is to render a raster png of the same size. Also, since the logo is part of both this project, backstrokeapp/www, and the dashboard, backstrokeapp/dashboard, you should be able to get two pull requests out of this.

Thanks for contributing!

**Comment by kosijer** [comment]
I'm on it. :)

**Comment by kosijer** [comment]
I'm getting some test errors that I can't see on PR. I guess you need to rebuild it. Cheers

**Comment by 1egoman** [comment]
@kosijer I did something funky in ci, it should be good now. 

Anyway, both are merged. Thanks for the contribution!
